; SCREENBOX — configuration bundle (ES-KDE)

[ScreenBox]
Autostart=0
SessionMonitor=0

[SplashScreen]
EnableIntro=1
FileName="ps2.mp4"
FilePath="default"
RandomVideo=1
VideoDelay=800
WaitForVideoEnd=1
GamepadVideoKill=1

[BackgroundMusic]
EnableMusic=1
FileName="Le Brick - Morning - Extended Mix.ogg"
FilePath="default"
RandomMusic=1
Volume=80

[EmulationStation]
Fullscreen=1
FullscreenBorderless=1
FocusDelay=500
